from flask import Flask, jsonify
import requests

app = Flask(__name__)

# ====== BẢNG THUẬT TOÁN (MÀY CỨ DÁN FULL 8.000 DÒNG VÀO) ======
prediction_table = {
    "XXXXXXTXXXXX": "Xỉu",
  "XXXXXTXXXXXX": "Xỉu",
  "XXXXTXXXXXXX": "Xỉu",
  "XXXTXXXXXXXX": "Tài",
  "XXTXXXXXXXXT": "Tài",
  "XTXXXXXXXXTX": "Tài",
  "TXXXXXXXXTXT": "Xỉu",
  "XXXXXXXXTXTX": "Tài",
  "XXXXXXXTXTXT": "Tài",
  "XXXXXXTXTXTT": "Tài",
  "XXXXXTXTXTTT": "Tài",
  "XXXXTXTXTTTT": "Xỉu",
  "XXXTXTXTTTTX": "Tài",
  "XXTXTXTTTTXT": "Tài",
  "XTXTXTTTTXTT": "Xỉu",
  "TXTXTTTTXTTX": "Xỉu",
  "XTXTTTTXTTXX": "Xỉu",
  "TXTTTTXTTXXX": "Xỉu",
  "XTTTTXTTXXXX": "Tài",
  "TTTTXTTXXXXT": "Tài",
  "TTTXTTXXXXTT": "Xỉu",
  "TTXTTXXXXTTX": "Xỉu",
  "TXTTXXXXTTXX": "Xỉu",
  "XTTXXXXTTXXX": "Tài",
  "TTXXXXTTXXXT": "Tài",
  "TXXXXTTXXXTX": "Xỉu",
  "XXXXTTXXXTXX": "Tài",
  "XXXTTXXXTXXT": "Tài",
  "XXTTXXXTXXTT": "Xỉu",
  "XTTXXXTXXTTX": "Tài",
  "TTXXXTXXTTXT": "Xỉu",
  "TXXXTXXTTXTX": "Tài",
  "XXXTXXTTXTXX": "Tài",
  "XXTXXTTXTXXT": "Tài",
  "XTXXTTXTXXTT": "Tài",
  "TXXTTXTXXTTT": "Xỉu",
  "XXTTXTXXTTTX": "Xỉu",
  "XTTXTXXTTTXX": "Xỉu",
  "TTXTXXTTTXXX": "Xỉu",
  "TXTXXTTTXXXX": "Tài",
  "XTXXTTTXXXXT": "Xỉu",
  "TXXTTTXXXXTX": "Xỉu",
  "XXTTTXXXXTXX": "Xỉu",
  "XTTTXXXXTXXX": "Xỉu",
  "TTTXXXXTXXXX": "Xỉu",
  "TTXXXXTXXXXX": "Xỉu",
  "TXXXXTXXXXXX": "Tài",
  "XXXXTXXXXXXT": "Tài",
  "XXXTXXXXXXTT": "Tài",
  "XXTXXXXXXTTT": "Tài",
  "XTXXXXXXTTTT": "Tài",
  "TXXXXXXTTTTT": "Xỉu",
  "XXXXXXTTTTTX": "Xỉu",
  "XXXXXTTTTTXX": "Xỉu",
  "XXXXTTTTTXXX": "Xỉu",
  "XXXTTTTTXXXX": "Xỉu",
  "XXTTTTTXXXXX": "Xỉu",
  "XTTTTTXXXXXT": "Xỉu",
  "TTTTTXXXXXTX": "Tài",
  "TTTTXXXXXTXT": "Tài",
  "TTTXXXXXTXTT": "Xỉu",
  "TTXXXXXTXTTX": "Tài",
  "TXXXXXTXTTXT": "Tài",
  "XXXXXTXTTXTT": "Tài",
  "XXXXTXTTXTTT": "Xỉu",
  "XXXTXTTXTTTX": "Xỉu",
  "XXTXTTXTTTXX": "Tài",
  "XTXTTXTTTXXT": "Tài",
  "TXTTXTTTXXTT": "Tài",
  "XTTXTTTXXTTX": "Tài",
  "TTXTTTXXTTXT": "Tài",
  "TXTTTXXTTXTT": "Xỉu",
  "XTTTXXTTXTTX": "Xỉu",
  "TTTXXTTXTTXX": "Tài",
  "TTXXTTXTTXXT": "Xỉu",
  "TXXTTXTTXXTX": "Xỉu",
  "XXTTXTTXXTXX": "Xỉu",
  "XTTXTTXXTXXX": "Xỉu",
  "TTXTTXXTXXXX": "Xỉu",
  "TXTTXXTXXXXX": "Xỉu",
  "XTTXXTXXXXXX": "Xỉu",
  "TTXXTXXXXXXX": "Xỉu",
  "TXXTXXXXXXXX": "Tài",
  "XTXXXXXXXXTT": "Xỉu",
  "TXXXXXXXXTTX": "Xỉu",
  "XXXXXXXXTTXX": "Tài",
  "XXXXXXXTTXXT": "Xỉu",
  "XXXXXXTTXXTX": "Xỉu",
  "XXXXXTTXXTXX": "Tài",
  "XXXXTTXXTXXT": "Xỉu",
  "XXXTTXXTXXTT": "Xỉu",
  "XXTTXXTXXTTX": "Tài",
  "XTTXXTXXTTXT": "Tài",
  "TTXXTXXTTXTT": "Tài",
  "TXXTXXTTXTTT": "Tài",
  "XXTXXTTXTTTT": "Tài",
  "XTXXTTXTTTTT": "Xỉu",
  "TXXTTXTTTTTX": "Tài",
  "XXTTXTTTTTXT": "Xỉu",
  "XTTXTTTTTXTX": "Tài",
  "TTXTTTTTXTXT": "Xỉu",
  "TXTTTTTXTXTX": "Xỉu",
  "XTTTTTXTXTXX": "Xỉu",
  "TTTTTXTXTXXX": "Xỉu",
  "TTTTXTXTXXXT": "Xỉu",
  "TTTXTXTXXXTX": "Tài",
  "TTXTXTXXXTXT": "Xỉu",
  "TXTXTXXXTXTX": "Tài",
  "XTXTXXXTXTXT": "Xỉu",
  "TXTXXXTXTXTX": "Tài",
  "XTXXXTXTXTXT": "Tài",
  "TXXXTXTXTXTT": "Xỉu",
  "XXXTXTXTXTTX": "Tài",
  "XXTXTXTXTTXT": "Tài",
  "XTXTXTXTTXTT": "Xỉu",
  "TXTXTXTTXTTX": "Tài",
  "XTXTXTTXTTXT": "Tài",
  "TXTXTTXTTXTT": "Tài",
  "XTXTTXTTXTTT": "Xỉu",
  "TXTTXTTXTTTX": "Xỉu",
  "XTTXTTXTTTXX": "Tài",
  "TTXTTXTTTXXT": "Tài",
  "XTTXTTTXXTTT": "Xỉu",
  "TTXTTTXXTTTX": "Tài",
  "TXTTTXXTTTXT": "Xỉu",
  "XTTTXXTTTXTX": "Xỉu",
  "TTTXXTTTXTXX": "Xỉu",
  "TTXXTTTXTXXX": "Xỉu",
  "TXXTTTXTXXXX": "Xỉu",
  "XXTTTXTXXXXX": "Tài",
  "XTTTXTXXXXXT": "Xỉu",
  "TTTXTXXXXXTX": "Tài",
  "TTXTXXXXXTXT": "Xỉu",
  "TXTXXXXXTXTX": "Tài",
  "XTXXXXXTXTXT": "Tài",
  "TXXXXXTXTXTT": "Xỉu",
  "XXXXXTXTXTTX": "Xỉu",
  "XXXXTXTXTTXX": "Tài",
  "XXXTXTXTTXXT": "Tài",
  "XXTXTXTTXXTT": "Tài",
  "XTXTXTTXXTTT": "Xỉu",
  "TXTXTTXXTTTX": "Xỉu",
  "XTXTTXXTTTXX": "Xỉu",
  "TXTTXXTTTXXX": "Tài",
  "XTTXXTTTXXXT": "Xỉu",
  "TTXXTTTXXXTX": "Tài",
  "TXXTTTXXXTXT": "Tài",
  "XXTTTXXXTXTT": "Tài",
  "XTTTXXXTXTTT": "Xỉu",
  "TTTXXXTXTTTX": "Tài",
  "TTXXXTXTTTXT": "Xỉu",
  "TXXXTXTTTXTX": "Xỉu",
  "XXXTXTTTXTXX": "Xỉu",
  "XXTXTTTXTXXX": "Xỉu",
  "XTXTTTXTXXXX": "Xỉu",
  "TXTTTXTXXXXX": "Xỉu",
  "XTTTXTXXXXXX": "Tài",
  "TTTXTXXXXXXT": "Xỉu",
  "TTXTXXXXXXTX": "Xỉu",
  "TXTXXXXXXTXX": "Tài",
  "XTXXXXXXTXXT": "Xỉu",
  "TXXXXXXTXXTX": "Xỉu",
  "XXXXXXTXXTXX": "Tài",
  "XXXXXTXXTXXT": "Tài",
  "XXXXTXXTXXTT": "Xỉu",
  "XXXTXXTXXTTX": "Tài",
  "XXTXXTXXTTXT": "Tài",
  "XTXXTXXTTXTT": "Xỉu",
  "TXXTXXTTXTTX": "Tài",
  "XXTXXTTXTTXT": "Xỉu",
  "XTXXTTXTTXTX": "Xỉu",
  "TXXTTXTTXTXX": "Xỉu",
  "XXTTXTTXTXXX": "Xỉu",
  "XTTXTTXTXXXX": "Tài",
  "TTXTTXTXXXXT": "Xỉu",
  "TXTTXTXXXXTX": "Xỉu",
  "XTTXTXXXXTXX": "Xỉu",
  "TTXTXXXXTXXX": "Tài",
  "TXTXXXXTXXXT": "Tài",
  "XTXXXXTXXXTT": "Xỉu",
  "TXXXXTXXXTTX": "Xỉu",
  "XXXXTXXXTTXX": "Tài",
  "XXXTXXXTTXXT": "Xỉu",
  "XXTXXXTTXXTX": "Xỉu",
  "XTXXXTTXXTXX": "Tài",
  "TXXXTTXXTXXT": "Xỉu",
  "XXXTTXXTXXTX": "Tài",
  "XXTTXXTXXTXX": "Xỉu",
  "XTTXXTXXTXXX": "Xỉu",
  "TTXXTXXTXXXX": "Xỉu",
  "TXXTXXTXXXXX": "Tài",
  "XXTXXTXXXXXT": "Xỉu",
  "XTXXTXXXXXTX": "Tài",
  "TXXTXXXXXTXT": "Tài",
  "XXTXXXXXTXTT": "Xỉu",
  "XTXXXXXTXTTX": "Xỉu",
  "TXXXXXTXTTXX": "Xỉu",
  "XXXXXTXTTXXX": "Tài",
  "XXXXTXTTXXXT": "Xỉu",
  "XXXTXTTXXXTX": "Tài",
  "XXTXTTXXXTXT": "Xỉu",
  "XTXTTXXXTXTX": "Tài",
  "TXTTXXXTXTXT": "Tài",
  "XTTXXXTXTXTT": "Xỉu",
  "TTXXXTXTXTTX": "Tài",
  "TXXXTXTXTTXT": "Tài",
  "XXXTXTXTTXTT": "Tài",
  "XXTXTXTTXTTT": "Tài",
  "XTXTXTTXTTTT": "Xỉu",
  "TXTXTTXTTTTX": "Xỉu",
  "XTXTTXTTTTXX": "Tài",
  "TXTTXTTTTXXT": "Tài",
  "XTTXTTTTXXTT": "Tài",
  "TTXTTTTXXTTT": "Tài",
  "TXTTTTXXTTTT": "Tài",
  "XTTTTXXTTTTT": "Xỉu",
  "TTTTXXTTTTTX": "Xỉu",
  "TTTXXTTTTTXX": "Xỉu",
  "TTXXTTTTTXXX": "Xỉu",
  "TXXTTTTTXXXX": "Xỉu",
  "XTTTTTXXXXXX": "Tài",
  "TTTTTXXXXXXT": "Xỉu",
  "TTTTXXXXXXTX": "Xỉu",
  "TTTXXXXXXTXX": "Tài",
  "TTXXXXXXTXXT": "Tài",
  "TXXXXXXTXXTT": "Tài",
  "XXXXXXTXXTTT": "Xỉu",
  "XXXXXTXXTTTX": "Xỉu",
  "XXXXTXXTTTXX": "Xỉu",
  "XXXTXXTTTXXX": "Tài",
  "XXTXXTTTXXXT": "Xỉu",
  "XTXXTTTXXXTX": "Xỉu",
  "TXXTTTXXXTXX": "Xỉu",
  "XXTTTXXXTXXX": "Tài",
  "XTTTXXXTXXXT": "Xỉu",
  "TTTXXXTXXXTX": "Xỉu",
  "TTXXXTXXXTXX": "Tài",
  "TXXXTXXXTXXT": "Tài",
  "XXXTXXXTXXTT": "Xỉu",
  "XXTXXXTXXTTX": "Tài",
  "XTXXXTXXTTXT": "Xỉu",
  "XXXTXXTTXTXT": "Xỉu",
  "XXTXXTTXTXTX": "Xỉu",
  "XTXXTTXTXTXX": "Xỉu",
  "TXXTTXTXTXXX": "Xỉu",
  "XXTTXTXTXXXX": "Tài",
  "XTTXTXTXXXXT": "Xỉu",
  "TTXTXTXXXXTX": "Xỉu",
  "TXTXTXXXXTXX": "Tài",
  "XTXTXXXXTXXT": "Xỉu",
  "TXTXXXXTXXTX": "Xỉu",
  "XTXXXXTXXTXX": "Xỉu",
  "TXXXXTXXTXXX": "Xỉu",
  "XXXXTXXTXXXX": "Tài",
  "XXXTXXTXXXXT": "Tài",
  "XXTXXTXXXXTT": "Tài",
  "XTXXTXXXXTTT": "Tài",
  "TXXTXXXXTTTT": "Tài",
  "XXTXXXXTTTTT": "Tài",
  "XTXXXXTTTTTT": "Xỉu",
  "TXXXXTTTTTTX": "Tài",
  "XXXXTTTTTTXT": "Xỉu",
  "XXXTTTTTTXTX": "Tài",
  "XXTTTTTTXTXT": "Tài",
  "XTTTTTTXTXTT": "Xỉu",
  "TTTTTTXTXTTX": "Xỉu",
  "TTTTTXTXTTXX": "Xỉu",
  "TTTTXTXTTXXX": "Tài",
  "TTTXTXTTXXXT": "Tài",
  "TTXTXTTXXXTT": "Tài",
  "TXTXTTXXXTTT": "Tài",
  "XTXTTXXXTTTT": "Tài",
  "TXTTXXXTTTTT": "Tài",
  "XTTXXXTTTTTT": "Xỉu",
  "TTXXXTTTTTTX": "Xỉu",
  "TXXXTTTTTTXX": "Xỉu",
  "XXXTTTTTTXXX": "Tài",
  "XXTTTTTTXXXT": "Tài",
  "XTTTTTTXXXTT": "Tài",
  "TTTTTTXXXTTT": "Xỉu",
  "TTTTTXXXTTTX": "Tài",
  "TTTTXXXTTTXX": "Tài",
  "TTTXXXTTTXXT": "Xỉu",
  "TTXXXTTTXXTX": "Tài",
  "TXXXTTTXXTXT": "Tài",
  "XXXTTTXXTXTT": "Tài",
  "XXTTTXXTXTTT": "Tài",
  "XTTTXXTXTTTT": "Tài",
  "TTTXXTXTTTTT": "Tài",
  "TTXXTXTTTTTT": "Xỉu",
  "TXXTXTTTTTTT": "Xỉu",
  "XXTXTTTTTTTX": "Xỉu",
  "XTXTTTTTTTXX": "Xỉu",
  "TXTTTTTTTXXX": "Tài",
  "XTTTTTTTXXXT": "Tài",
  "TTTTTTTXXXTT": "Tài",
  "TTTTXXXTTTXT": "Xỉu",
  "TTTXXXTTTXTT": "Tài",
  "TTXXXTTTXTTT": "Tài",
  "TXXXTTTXTTTT": "Xỉu",
  "XXXTTTXTTTTX": "Tài",
  "XXTTTXTTTTXT": "Tài",
  "XTTTXTTTTXTT": "Tài",
  "TTTXTTTTXTTT": "Xỉu",
  "TTXTTTTXTTTX": "Xỉu",
  "TXTTTTXTTTXX": "Xỉu",
  "XTTTTXTTTXXX": "Xỉu",
  "TTTTXTTTXXXX": "Xỉu",
  "TTTXTTTXXXXX": "Tài",
  "TTXTTTXXXXXT": "Tài",
  "TXTTTXXXXXTT": "Xỉu",
  "XTTTXXXXXTTX": "Xỉu",
  "TTTXXXXXTTXX": "Tài",
  "TTXXXXXTTXXT": "Xỉu",
  "TXXXXXTTXXTX": "Xỉu",
  "XXTTXXTXXTXT": "Tài",
  "XTTXXTXXTXTT": "Tài",
  "TTXXTXXTXTTT": "Tài",
  "TXXTXXTXTTTT": "Xỉu",
  "XXTXXTXTTTTX": "Xỉu",
  "XTXXTXTTTTXX": "Xỉu",
  "TXXTXTTTTXXX": "Tài",
  "XXTXTTTTXXXT": "Tài",
  "XTXTTTTXXXTT": "Tài",
  "TXTTTTXXXTTT": "Xỉu",
  "XTTTTXXXTTTX": "Tài",
  "TTTXXXTTTXTX": "Xỉu",
  "TTXXXTTTXTXX": "Xỉu",
  "TXXXTTTXTXXX": "Xỉu",
  "XXXTTTXTXXXX": "Tài",
  "XXTTTXTXXXXT": "Xỉu",
  "XTTTXTXXXXTX": "Tài",
  "TTTXTXXXXTXT": "Tài",
  "TTXTXXXXTXTT": "Xỉu",
  "TXTXXXXTXTTX": "Xỉu",
  "XTXXXXTXTTXX": "Xỉu",
  "TXXXXTXTTXXX": "Xỉu",
  "XXXXTXTTXXXX": "Tài",
  "XXXTXTTXXXXT": "Tài",
  "XXTXTTXXXXTT": "Xỉu",
  "XTXTTXXXXTTX": "Xỉu",
  "TXXXXTTXXXTT": "Xỉu",
  "XXXXTTXXXTTX": "Tài",
  "XXXTTXXXTTXT": "Tài",
  "XXTTXXXTTXTT": "Tài",
  "XTTXXXTTXTTT": "Tài",
  "TTXXXTTXTTTT": "Xỉu",
  "TXXXTTXTTTTX": "Xỉu",
  "XXXTTXTTTTXX": "Tài",
  "XXTTXTTTTXXT": "Xỉu",
  "XTTXTTTTXXTX": "Tài",
  "TTXTTTTXXTXT": "Tài",
  "TXTTTTXXTXTT": "Tài",
  "XTTTTXXTXTTT": "Tài",
  "TTTTXXTXTTTT": "Tài",
  "TXXTXTTTTTTX": "Tài",
  "XXTXTTTTTTXT": "Xỉu",
  "XTXTTTTTTXTX": "Tài",
  "TXTTTTTTXTXT": "Xỉu",
  "XTTTTTTXTXTX": "Xỉu",
  "TTTTTTXTXTXX": "Xỉu",
  "TTTTXTXTXXXX": "Tài",
  "TTTXTXTXXXXT": "Tài",
  "TTXTXTXXXXTT": "Xỉu",
  "TXTXTXXXXTTX": "Xỉu",
  "XTXTXXXXTTXX": "Tài",
  "TXTXXXXTTXXT": "Tài",
  "XTXXXXTTXXTT": "Tài",
  "TXXXXTTXXTTT": "Tài",
  "XXXXTTXXTTTT": "Xỉu",
  "XXXTTXXTTTTX": "Xỉu",
  "XXTTXXTTTTXX": "Tài",
  "XTTXXTTTTXXT": "Xỉu",
  "TTXXTTTTXXTX": "Tài",
  "TXXTTTTXXTXT": "Xỉu",
  "XXTTTTXXTXTX": "Xỉu",
  "XTTTTXXTXTXX": "Xỉu",
  "TTTTXXTXTXXX": "Xỉu",
  "TTTXXTXTXXXX": "Xỉu",
  "TTXXTXTXXXXX": "Tài",
  "TXXTXTXXXXXT": "Tài",
  "XXTXTXXXXXTT": "Tài",
  "XTXTXXXXXTTT": "Xỉu",
  "TXTXXXXXTTTX": "Tài",
  "XTXXXXXTTTXT": "Xỉu",
  "TXXXXXTTTXTX": "Tài",
  "XXXXXTTTXTXT": "Xỉu",
  "XXXXTTTXTXTX": "Xỉu",
  "XXXTTTXTXTXX": "Xỉu",
  "XXTTTXTXTXXX": "Tài",
  "XTTTXTXTXXXT": "Tài",
  "TTTXTXTXXXTT": "Xỉu",
  "TTXTXTXXXTTX": "Tài",
  "TXTXTXXXTTXT": "Xỉu",
  "XTXTXXXTTXTX": "Tài",
  "TXTXXXTTXTXT": "Tài",
  "XTXXXTTXTXTT": "Xỉu",
  "TXXXTTXTXTTX": "Tài",
  "XXXTTXTXTTXT": "Xỉu",
  "XXTTXTXTTXTX": "Tài",
  "XTTXTXTTXTXT": "Xỉu",
  "TTXTXTTXTXTX": "Tài",
  "TXTXTTXTXTXT": "Xỉu",
  "XTXTTXTXTXTX": "Tài",
  "TXTTXTXTXTXT": "Tài",
  "XTTXTXTXTXTT": "Xỉu",
  "TTXTXTXTXTTX": "Xỉu",
  "TXTXTXTXTTXX": "Xỉu",
  "XTXTXTXTTXXX": "Tài",
  "TXTXTXTTXXXT": "Xỉu",
  "XTXTXTTXXXTX": "Tài",
  "TXTXTTXXXTXT": "Tài",
  "XTXTTXXXTXTT": "Tài",
  "TXTTXXXTXTTT": "Tài",
  "XTTXXXTXTTTT": "Xỉu",
  "TTXXXTXTTTTX": "Tài",
  "TXXXTXTTTTXT": "Xỉu",
  "XXXTXTTTTXTX": "Xỉu",
  "XXTXTTTTXTXX": "Tài",
  "XTXTTTTXTXXT": "Tài",
  "TXTTTTXTXXTT": "Tài",
  "XTTTTXTXXTTT": "Tài",
  "TTTTXTXXTTTT": "Xỉu",
"XXXXXXTTTTXXX": "Xỉu",
"XXXXXXTTTXTTT": "Tài",
"XXXXXXTTTXTTX": "Xỉu",
"XXXXXXTTTXTXT": "Xỉu",
"XXXXXXTTTXTXX": "Xỉu",
"XXXXXXTTTXXTT": "Tài",
"XXXXXXTTTXXTX": "Tài",
"XXXXXXTTTXXXT": "Xỉu",
"XXXXXXTTTXXXX": "Xỉu",
"XXXXXXTTXTTTT": "Xỉu",
"XXXXXXTTXTTTX": "Tài",
"XXXXXXTTXTTXT": "Xỉu",
"XXXXXXTTXTTXX": "Xỉu",
"XXXXXXTTXTXTT": "Tài",
"XXXXXXTTXTXTX": "Tài",
"XXXXXXTTXTXXT": "Xỉu",
"XXXXXXTTXTXXX": "Xỉu",
"XXXXXXTTXXTTT": "Tài",
"XXXXXXTTXXTTX": "Xỉu",
"XXXXXXTTXXTXT": "Xỉu",
"XXXXXXTTXXTXX": "Xỉu",
"XXXXXXTTXXXTT": "Tài",
"XXXXXXTTXXXTX": "Tài",
"XXXXXXTTXXXXT": "Xỉu",
"XXXXXXTTXXXXX": "Xỉu",
"XXXXXXTXTTTTT": "Tài",
"XXXXXXTXTTTTX": "Tài",
"XXXXXXTXTTTXT": "Xỉu",
"XXXXXXTXTTTXX": "Xỉu",
"XXXXXXTXTTXTT": "Tài",
"XXXXXXTXTTXTX": "Tài",
"XXXXXXTXTTXXT": "Tài",
"XXXXXXTXTTXXX": "Xỉu",
"XXXXXXTXTXTTT": "Tài",
"XXXXXXTXTXTTX": "Xỉu",
"XXXXXXTXTXTXT": "Xỉu",
"XXXXXXTXTXTXX": "Xỉu",
"XXXXXXTXTXXTT": "Tài",
"XXXXXXTXTXXTX": "Tài",
"XXXXXXTXTXXXT": "Xỉu",
"XXXXXXTXTXXXX": "Xỉu",
"XXXXXXTXXTTTT": "Xỉu",
"XXXXXXTXXTTTX": "Tài",
"XXXXXXTXXTTXT": "Xỉu",
"XXXXXXTXXTTXX": "Xỉu",
"XXXXXXTXXTXTT": "Tài",
"XXXXXXTXXTXTX": "Tài",
"XXXXXXTXXTXXT": "Xỉu",
"XXXXXXTXXTXXX": "Xỉu",
"XXXXXXTXXXTTT": "Tài",
"XXXXXXTXXXTTX": "Xỉu",
"XXXXXXTXXXTXT": "Xỉu",
"XXXXXXTXXXTXX": "Xỉu",
"XXXXXXTXXXXTT": "Tài",
"XXXXXXTXXXXTX": "Tài",
"XXXXXXTXXXXXT": "Xỉu",
"XXXXXXTXXXXXX": "Xỉu",
"XXXXXXXTTTTTT": "Tài",
"XXXXXXXTTTTTX": "Tài",
"XXXXXXXTTTTXT": "Xỉu",
"XXXXXXXTTTTXX": "Xỉu",
"XXXXXXXTTTXTT": "Tài",
"XXXXXXXTTTXTX": "Tài",
"XXXXXXXTTTXXT": "Xỉu",
"XXXXXXXTTTXXX": "Xỉu",
"XXXXXXXTTXTTT": "Tài",
"XXXXXXXTTXTTX": "Tài",
"XXXXXXXTTXTXT": "Xỉu",
"XXXXXXXTTXTXX": "Xỉu",
"XXXXXXXTTXXTT": "Tài",
"XXXXXXXTTXXTX": "Tài",
"XXXXXXXTTXXXT": "Xỉu",
"XXXXXXXTTXXXX": "Xỉu",
"XXXXXXXTXTTTT": "Xỉu",
"XXXXXXXTXTTTX": "Tài",
"XXXXXXXTXTTXT": "Xỉu",
"XXXXXXXTXTTXX": "Xỉu",
"XXXXXXXTXTXTT": "Tài",
"XXXXXXXTXTXTX": "Tài",
"XXXXXXXTXTXXT": "Xỉu",
"XXXXXXXTXTXXX": "Xỉu",
"XXXXXXXTXXTTT": "Xỉu",
"XXXXXXXTXXTTX": "Xỉu",
"XXXXXXXTXXTXT": "Xỉu",
"XXXXXXXTXXTXX": "Xỉu",
"XXXXXXXTXXXTT": "Tài",
"XXXXXXXTXXXTX": "Tài",
"XXXXXXXTXXXXT": "Xỉu",
"XXXXXXXTXXXXX": "Xỉu",
"XXXXXXXXTTTTT": "Tài",
"XXXXXXXXTTTTX": "Tài",
"XXXXXXXXTTTXT": "Xỉu",
"XXXXXXXXTTTXX": "Xỉu",
"XXXXXXXXTTXTT": "Tài",
"XXXXXXXXTTXTX": "Tài",
"XXXXXXXXTTXXT": "Xỉu",
"XXXXXXXXTTXXX": "Xỉu",
"XXXXXXXXTXTTT": "Xỉu",
"XXXXXXXXTXTTX": "Xỉu",
"XXXXXXXXTXTXT": "Xỉu",
"XXXXXXXXTXTXX": "Xỉu",
"XXXXXXXXTXXTT": "Tài",
"XXXXXXXXTXXTX": "Tài",
"XXXXXXXXTXXXT": "Xỉu",
"XXXXXXXXTXXXX": "Xỉu",
"XXXXXXXXXTTTT": "Xỉu",
"XXXXXXXXXTTTX": "Tài",
"XXXXXXXXXTTXT": "Xỉu",
"XXXXXXXXXTTXX": "Xỉu",
"XXXXXXXXXTXTT": "Tài",
"XXXXXXXXXTXTX": "Tài",
"XXXXXXXXXTXXT": "Xỉu",
"XXXXXXXXXTXXX": "Xỉu",
"XXXXXXXXXXTTT": "Xỉu",
"XXXXXXXXXXTTX": "Xỉu",
"XXXXXXXXXXTXT": "Xỉu",
"XXXXXXXXXXTXX": "Xỉu",
"XXXXXXXXXXXTT": "Tài",
"XXXXXXXXXXXTX": "Tài",
"XXXXXXXXXXXXT": "Xỉu",
"XXXXXXXXXXXXX": "Xỉu",
}

# ====== LẤY DATA + DỰ ĐOÁN ======
def get_taixiu_data():
    url = "https://wtxmd52.tele68.com/v1/txmd5/sessions"
    try:
        res = requests.get(url, timeout=8)
        res.raise_for_status()
        data = res.json()

        if "list" not in data or len(data["list"]) < 15:
            return {"error": "Không đủ lịch sử cầu"}

        recent = data["list"][:15]

        # ====== BUILD CẦU (CŨ → MỚI) ======
        cau = ""
        for item in reversed(recent):
            raw = item.get("resultTruyenThong", "").upper()
            if raw == "TAI":
                cau += "T"
            elif raw == "XIU":
                cau += "X"

        # ====== MATCH THUẬT TOÁN (KHÔNG ÉP 12) ======
        du_doan = "Không xác định"
        key_used = ""

        # ưu tiên match key dài trước
        for k in sorted(prediction_table.keys(), key=len, reverse=True):
            if cau.endswith(k):
                du_doan = prediction_table[k]
                key_used = k
                break

        # ====== FALLBACK (KHÔNG ĐỂ API CHẾT) ======
        if du_doan == "Không xác định":
            last12 = cau[-12:]
            t = last12.count("T")
            x = last12.count("X")
            if t > x:
                du_doan = "Tài"
            elif x > t:
                du_doan = "Xỉu"
            else:
                du_doan = "Không vào"
            key_used = last12

        newest = recent[0]
        dice = newest.get("dices", [0, 0, 0])
        tong = newest.get("point", sum(dice))

        do_tin_cay = min(len(key_used) * 7, 98)

        return {
            "phien": newest.get("id"),
            "xucxac1": dice[0],
            "xucxac2": dice[1],
            "xucxac3": dice[2],
            "tong": tong,
            "ketqua": "Tài" if tong >= 11 else "Xỉu",
            "du_doan": du_doan,
            "do_tin_cay": do_tin_cay,
            "cau": key_used,
            "id": "lc79"
        }

    except Exception as e:
        return {"error": str(e)}

# ====== API ======
@app.route("/", methods=["GET"])
def taixiu():
    return jsonify(get_taixiu_data())
